wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1634224961
    t:
      1:
      - 1
      2:
      - 1
      4: 3.8.10
      5: 0.12.0
      8:
      - 5
batch_size:
  desc: null
  value: 128
beta1:
  desc: null
  value: 0.5
lr:
  desc: null
  value: 0.0002
num_epochs:
  desc: null
  value: 30
