wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.0
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1638691619
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 3
      - 5
      3:
      - 2
      4: 3.8.10
      5: 0.12.0
      8:
      - 5
attention_heads:
  desc: null
  value: 4
batch_size:
  desc: null
  value: 64
decoder_layers:
  desc: null
  value: 3
dropout:
  desc: null
  value: 0.2
emb_dim:
  desc: null
  value: 32
encoder_layers:
  desc: null
  value: 3
ffn_dim:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.0001
nepochs:
  desc: null
  value: 50
patience:
  desc: null
  value: 10
